name: eit
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - tqdm
  - h5py
  - hdf5
  - scipy
  - numpy
  - matplotlib
  - python
  - pytorch-cuda=11.8
  - torchvision
  - pytorch
  - hdf5storage
  - cuda-toolkit=11.8
